name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest