name: Hotfix Zip site-packages
run-name: ${{github.ref_name}} Zip site-packages
on:
  push:
    branches:
      - hotfix/*
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # step 1
      - uses: actions/checkout@v3

      # step 2
      - name: Install poetry
        run: pipx install poetry

      # step 3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"

      # step 4
      - name: Install dependencies
        run: poetry install

      # step 5
      - name: Run pytest
        run: poetry run pytest
      
      - name: Check path Site-packages
        run: |
          find `poetry env info -p` -type d -name 'site-packages' | echo
      # step 6
      - name: Create Zipfile archive of dependencies
        run: |
          find `poetry env info -p` -type d -name 'site-packages' | xargs zip -9r api.zip

      # # Step 7
      # - name: Add App to Zip file
      #   run: |
      #     cd app && zip -g ../api.zip -r . && cd -

      # # Step 8
      # - name: Upload zip file artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: api
      #     path: api.zip

