name: Hotfix Zip site-packages
run-name: Zip site-packages (${{github.ref_name}})
on:
  push:
    branches:
      - hotfix/**
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # step 1
      - uses: actions/checkout@v3

      # step 2
      - name: Install poetry
        run: pipx install poetry

      # step 3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"

      # step 4
      - name: Install dependencies
        run: poetry install

      # step 5
      - name: Run pytest
        run: poetry run pytest
      
      - name: Zip Site-packes 
        run: |
          find `poetry env info -p` -type d -name 'site-packages' -print | xargs -I % cp -R % .
          mv site-packages python
          zip -r python.zip python
          unzip -l python.zip
      
      - name: Zip app
        run: |
          zip -r app.zip app
          unzip -l app.zip

      - name: Upload python.zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: python.zip
          path: python.zip

      - name: Upload app.zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.zip
          path: app.zip
      
      # - name: Upload app.zip file artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: bin.zip
      #     path: bin.zip
      
      
      
